### ISSUE TITLE
[1.12.2] Causes a crash whenever you place Mekanism storage or transfer blocks

### ISSUE THREAD

**Issue by razage** [TominoCZ/FancyBlockParticles#36]
When you place any pipes or storage (energy cube, tank, etc) from Mekanism, having this mod causes a crash because of a null value. I believe this is related to issue #35 because these blocks _also_ have tags.

**Comment by TominoCZ** [comment]
provide crashlog please.

**Comment by razage** [comment]
https://pastebin.com/iJjtn3vw

**Comment by TominoCZ** [comment]
I don't see how my mod would cause that. Did you try it with the mod disabled in the FBP menu (it's the FBP button)?

**Comment by razage** [comment]
I didn't try anything via in-game configurations, but I did run the pack with your mod disabled and removed, and it doesn't have this issue.

**Comment by TominoCZ** [comment]
hmm.. weird..
Does it crash immediately after right clicking or after the animation ends?

**Comment by razage** [comment]
I disabled it from the menu in-game, and both of my issues are fixed, just like removing it or disabling it via the twitch launcher.

With Mekanism specifically, as soon as I right click the game crashes. I don't get to see the block placed. I _think_ I recall you or someone else mentioning the fancy placement being a culprit?

**Comment by TominoCZ** [comment]
Yes.. the block placement animation feature is most likely why it crashes. Though I really don't understand why it does. The crashlog doesn't point to my mod at all.

I've looked at Mekanism's code to see where exactly it crashed aand it doesn't even make sense to me that it crashed in that particular part of code.. It just.. shouldn't happen..

Well it's pretty late for me. I'll see what I can do about it tomorrow.

**Comment by TominoCZ** [comment]
Ok.. although I still don't understand how this issue was really connected with what I changed in the code, I managed to finally fix it and it will be fixed in the upcoming version :)
